-- En este archivo deben estar tus ejercicios de consultas sql

-- 1. Empleados ordenados alfabéticamente (Z...A):
SELECT NOMBRES
FROM EMPLEADOS
ORDER BY NOMBRES DESC;


-- 2. Empleados de Soporte:
SELECT e.NOMBRES, p.PUESTO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID
WHERE p.PUESTO = 'Soporte';



-- 3. Nombres que terminan con 'o':
SELECT NOMBRES
FROM EMPLEADOS
WHERE NOMBRES LIKE '%o';


-- 4. Empleados en Carlos Paz:
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID
WHERE l.LOCALIDAD = 'Carlos Paz';



-- 5. Sueldos entre 10000 y 13000:SELECT E.NOMBRES, E.SUELDO, L.LOCALIDAD
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID
WHERE e.SUELDO BETWEEN 10000 AND 13000;



-- 6. Departamentos con más de 5 empleados:
SELECT d.DENOMINACION 
FROM DEPARTAMENTOS d
JOIN EMPLEADOS e ON d.ID = e.DEPARTAMENTO_ID
GROUP BY d.DENOMINACION
HAVING COUNT(e.ID) > 5;



-- 7. Empleados en Córdoba con puesto de Analista o Programador:
SELECT e.NOMBRES 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID
WHERE l.LOCALIDAD = 'Córdoba' 
AND (p.PUESTO = 'Analista' OR p.PUESTO = 'Programador');



-- 8. Sueldo medio de todos los empleados:
SELECT AVG(SUELDO) AS SueldoMedio
FROM EMPLEADOS;



-- 9. Máximo sueldo en el departamento 10:
SELECT MAX(SUELDO) AS MaxSueldo
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 10;


SELECT MIN(e.SUELDO) AS MinSueldo 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
WHERE p.PUESTO = 'Soporte';


-- 11. Suma de sueldos por puesto:
SELECT p.PUESTO, SUM(e.SUELDO) AS TotalSueldo 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
GROUP BY p.PUESTO;

